### ISSUE TITLE
Use tidyverse to create Rodent.Recip/Donor

### ISSUE THREAD

**Issue by cgreysongaito** [karl-cottenie/meta_transplant_microbiome#1]
#TODO: use tidyverse to create these two vectors
Lines 38-49

df_Transplant$Rodent.Recip <- df_Transplant$`Recipient Taxon` #Create a new column identical to recipient taxon column
df_Transplant$Rodent.Recip[df_Transplant$Rodent.Recip == 'mouse'] <- 'Rodent' #Replace various lab rodent models with 'Rodent'
df_Transplant$Rodent.Recip[df_Transplant$Rodent.Recip == 'Mice'] <- 'Rodent'
df_Transplant$Rodent.Recip[df_Transplant$Rodent.Recip == 'rat'] <- 'Rodent'
df_Transplant$Rodent.Recip[df_Transplant$Rodent.Recip == 'rats'] <- 'Rodent'
df_Transplant$Rodent.Recip[df_Transplant$Rodent.Recip != 'Rodent'] <- 'Other' #Replace all non-lab-rodent taxons to 'other'

df_Transplant$Rodent.Donor <- df_Transplant$`Donor Taxon` #Create a new column identical to donor taxon column
df_Transplant$Rodent.Donor[df_Transplant$Rodent.Donor == 'mouse'] <- 'Rodent' #Replace various lab rodent models with 'Rodent'
df_Transplant$Rodent.Donor[df_Transplant$Rodent.Donor == 'rat'] <- 'Rodent'
df_Transplant$Rodent.Donor[df_Transplant$Rodent.Donor != 'Rodent'] <- 'Other' #Replace all non-lab-rodent taxons to 'other'

**Comment by karl-cottenie** [comment]
One solution with [Commit 2018-11-20](https://github.com/karl-cottenie/meta_transplant_microbiome/commit/eb50c17218ada4e2e9c2585417de7caed11c87e7)
