### ISSUE TITLE
bars are different widths depending on how many catergories there are

### ISSUE THREAD

**Issue by cgreysongaito** [karl-cottenie/meta_transplant_microbiome#11]

**Comment by cgreysongaito** [comment]
plus some x axis integers and some have decimals

**Comment by karl-cottenie** [comment]
solved the x axis problem

**Comment by cgreysongaito** [comment]
and fixed different widths for different catergories. also decided to change to geom_bar because in a sense these catergories are not continuous nor are we binning anything (like a histogram)
