### ISSUE TITLE
Remove Number of Treatment Groups column from dataset?

### ISSUE THREAD

**Issue by cgreysongaito** [karl-cottenie/meta_transplant_microbiome#3]
Now that each row is a "transplant condition", do we need a column for number of treatment groups?

**Comment by karl-cottenie** [comment]
no, but we don't use it in our code, so I would just leave it in the data sheet, who knows when we need it.

**Comment by cgreysongaito** [comment]
So one issue with the Number of Treatment Groups is that when/if we publish this dataset, this column will be confusing because the number of treatment groups is not specifically for each row but for multiple rows (and possibly includes controls which have no tranplantations)

**Comment by karl-cottenie** [comment]
yes, but I just anticipated us publishing a dataset with only the relevant columns, not all the ones that we currently have. So I don't think we have to worry about it at this point. It becomes more of a problem if we actually will use this column for something.

**Comment by cgreysongaito** [comment]
Sounds good.
