### ISSUE TITLE
Discuss collapsing Recipient Microbiome

### ISSUE THREAD

**Issue by cgreysongaito** [karl-cottenie/meta_transplant_microbiome#7]
discuss collapsing recipient microbiome (4 & 5)

**Comment by karl-cottenie** [comment]
discussed, but not yet applied in the work sheet

**Comment by cgreysongaito** [comment]
So I am now confused because I have partly forgotten our conversation. Did we decide to collapse recipient microbiome to be three categories (similar to transplanted microbiome)? We did not change the Categories sheet of our excel file, so I am confused

**Comment by karl-cottenie** [comment]
I thought Tim made notes about this?

**Comment by cgreysongaito** [comment]
He remembers that we did decide to collapse recipient microbiome to the three categories. I have ensured that column contains 1-3 in the spreadsheet. I have updated the ecoreality categories.
